### ISSUE TITLE
Friendly creation dates display as one day behind

### ISSUE THREAD

**Issue by liwiz** [MartinSGill/TodoTxtJs#75]
Greetings,

I would like to report a small but glaring bug. When I enter a task containing a creation date, while the absolute date stored is correct, the relative (friendly) date is always one day behind. Curiously, the due date always shows up correctly.

For example, if I enter the following task on October 23,

`2014-10-23 testing due:2014-10-24`

the line will be rendered as

**Yesterday** testing **due:Tomorrow**

Whereas the expected behavior is

**Today** testing **due:Tomorrow**

This phenomenon is observed regardless of whether I enter the creation date manually or via the "**Create Date** : Automatically add a start date to new TODOs" option.

Would be happy to help you test. Thanks in advance!

**Comment by MartinSGill** [comment]
Fixed in 1.6

**Comment by liwiz** [comment]
Hi Martin, thank you for looking into this. Unfortunately I am still encountering the same bug in version 1.6.0. I've entered the following,

`(B) 2015-02-02 another test @work +test due:2015-02-07 `

and the creation date still shows up as "yesterday" even though my local date is 2015-02-02. I've attached a screenshot.

Do you think this may be time zone related? I am in UTC-05:00.

![todotxtjs-creation-date-bug](https://cloud.githubusercontent.com/assets/2948859/6009239/e615f9f6-aaf5-11e4-9d60-7c1487c7c930.png)

**Comment by roybaum** [comment]
I've noticed the same issue here in Central time. The funny thing is while the "create-date" is a day off, the "due dates" date works fine.
